apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: crccheck01-dev-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: crccheck01-dev.tdev.bam01.th
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: crccheck01-dev-service
                port:
                  number: 80
